#!/usr/bin/env node
// Builds the Claude Code skills published under skill/:
//   - tutuca        — copied locally from docs/skill/
//   - tutuca-source — wraps dist/tutuca.ext.js so the agent can grep it
//   - margaui       — cloned + generated from the margaui repo
//   - immutable-js  — cloned from the immutable-js repo's prebuilt skill
//
// Run with no args to build all; pass names to build a subset, e.g.
//   node scripts/build-skill.js tutuca
//
// skill/ is a generated artifact (gitignored, packed into the npm tarball via
// package.json "files"). It is NOT a source tree — edit docs/skill/, not
// skill/tutuca/. The `release`/`release-dry` scripts remove skill/ again right
// after publishing (`npm run clean-skill`) so a stale copy can't linger in the
// working tree and get mistaken for the source.
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const skillDir = resolve(repo, "skill");

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, { stdio: "inherit", ...opts });
}

function requireBin(cmd) {
  try {
    execFileSync(cmd, ["--version"], { stdio: "ignore" });
  } catch {
    process.stderr.write(`build-skill: required binary not found: ${cmd}\n`);
    process.exit(1);
  }
}

// Shallow-clone `repoUrl` into a temp dir, hand it to `fn(checkout, sha)`,
// then clean the temp dir up regardless of outcome.
function withClone(repoUrl, { branch } = {}, fn) {
  requireBin("git");
  const tmp = mkdtempSync(join(tmpdir(), "tutuca-skill-"));
  try {
    const cloneArgs = ["clone", "--depth", "1"];
    if (branch) cloneArgs.push("--branch", branch);
    cloneArgs.push(repoUrl, tmp);
    process.stdout.write(`cloning ${repoUrl}${branch ? ` (${branch})` : ""} → ${tmp}\n`);
    run("git", cloneArgs);

    const sha = execFileSync("git", ["-C", tmp, "rev-parse", "HEAD"], {
      encoding: "utf8",
    }).trim();
    process.stdout.write(`${repoUrl} commit: ${sha}\n`);

    return fn(tmp, sha);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

// --- tutuca: copied locally from docs/skill/ -------------------------------

// docs/skill/ IS the skill, laid out 1:1 with what ships (SKILL.md +
// frontmatter, the reference docs, and patterns/). Building is a plain
// recursive copy — adding or renaming a doc needs no change here.
function buildTutuca() {
  const srcDir = resolve(repo, "docs/skill");
  const outDir = resolve(skillDir, "tutuca");

  rmSync(outDir, { recursive: true, force: true });
  cpSync(srcDir, outDir, { recursive: true });
  process.stdout.write(`built skill/tutuca/ from docs/skill/ → ${outDir}\n`);
}

// --- tutuca-source: wraps dist/tutuca.ext.js -------------------------------

const TUTUCA_SOURCE_SKILL = `---
name: tutuca-source
description: The bundled framework source (\`dist/tutuca.ext.js\`) wrapped as a skill so the agent can grep it. Use only when debugging — to confirm what the framework actually does, trace an error from the framework, or find the implementation of a method you saw in a stack trace. Always reach for \`grep_skill_files\` first, then \`load_skill_file\` with \`startLine\`/\`endLine\` to read a window around a hit. Not for component-authoring guidance — use the \`tutuca\` skill for that.
---

<!-- This file is generated by scripts/build-skill.js. Do not edit. -->

# Tutuca source

The bundled framework that ships to users — the ESM at \`dist/tutuca.ext.js\`.
This skill exposes it as one file (\`tutuca.ext.js\`) so the agent can read
the implementation when needed.

## How to read it

- It is **one large file** (~3.8K lines). Loading it whole will flood your
  context — always \`grep_skill_files("tutuca-source", "<pattern>")\` first,
  then \`load_skill_file("tutuca-source", "tutuca.ext.js", { startLine, endLine })\`
  to pull a small window around a match.
- It is the **bundled** output: ESM, not minified, no source map. Class and
  function names match the original sources; comments do not survive.

## When to use

- A \`lint_component\` / \`render_component\` result mentions a framework
  function or error string you don't recognise — grep for it.
- A component crashes inside the framework — grep the error message or the
  framework function in the stack trace.
- A behavior is surprising and you want to confirm exactly what the framework
  does, not what the docs say it does.

**Don't** use this skill for *how to write* tutuca components — that's the
\`tutuca\` skill. Reach here only when you need to read the implementation.
`;

function buildTutucaSource() {
  const src = resolve(repo, "dist/tutuca.ext.js");
  const outDir = resolve(skillDir, "tutuca-source");

  if (!existsSync(src)) {
    process.stderr.write(
      `build-skill: ${src} not found — run \`npm run dist-ext\` (or \`dist-all\`) in the tutuca repo first\n`,
    );
    process.exit(1);
  }

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  cpSync(src, resolve(outDir, "tutuca.ext.js"));
  writeFileSync(resolve(outDir, "SKILL.md"), TUTUCA_SOURCE_SKILL);
  process.stdout.write(`built skill/tutuca-source/ from ${src} → ${outDir}\n`);
}

// --- margaui: cloned + generated from the margaui repo ---------------------

function buildMargaui() {
  const REPO_URL = "https://github.com/marianoguerra/margaui.git";
  const outDir = resolve(skillDir, "margaui");

  requireBin("npm");
  requireBin("python3");

  withClone(REPO_URL, {}, (tmp, sha) => {
    run("npm", ["install"], { cwd: tmp });
    run("npm", ["run", "playground"], { cwd: tmp });
    run("npm", ["run", "gen-skill"], { cwd: tmp });

    const generated = resolve(tmp, ".claude/skills/margaui");
    if (!existsSync(generated)) {
      process.stderr.write(`build-skill: gen-skill produced no output at ${generated}\n`);
      process.exit(1);
    }

    rmSync(outDir, { recursive: true, force: true });
    cpSync(generated, outDir, { recursive: true });
    process.stdout.write(`built skill/margaui/ from ${REPO_URL}@${sha} → ${outDir}\n`);
  });
}

// --- immutable-js: cloned from the immutable-js repo's prebuilt skill ------

function buildImmutable() {
  const REPO_URL = "https://github.com/marianoguerra/immutable-js.git";
  const BRANCH = "7.x";
  const UPSTREAM_SKILL = ".claude/skills/immutable-js";
  const outDir = resolve(skillDir, "immutable-js");

  withClone(REPO_URL, { branch: BRANCH }, (tmp, sha) => {
    const src = resolve(tmp, UPSTREAM_SKILL);
    if (!existsSync(resolve(src, "SKILL.md"))) {
      process.stderr.write(`build-skill: ${UPSTREAM_SKILL}/SKILL.md missing in clone\n`);
      process.exit(1);
    }

    rmSync(outDir, { recursive: true, force: true });
    cpSync(src, outDir, { recursive: true });
    process.stdout.write(
      `built skill/immutable-js/ from ${REPO_URL}@${sha} (${BRANCH}) → ${outDir}\n`,
    );
  });
}

// --- entry point -----------------------------------------------------------

const builders = {
  tutuca: buildTutuca,
  "tutuca-source": buildTutucaSource,
  margaui: buildMargaui,
  "immutable-js": buildImmutable,
};

const selected = process.argv.slice(2);
const names = selected.length > 0 ? selected : Object.keys(builders);

// A full build (no args) regenerates every skill — wipe skill/ first so stale
// files from older skill layouts can't linger at its root. A subset build
// leaves siblings intact; each builder still cleans its own subdirectory.
if (selected.length === 0) {
  rmSync(skillDir, { recursive: true, force: true });
  mkdirSync(skillDir, { recursive: true });
}

for (const name of names) {
  const builder = builders[name];
  if (!builder) {
    process.stderr.write(
      `build-skill: unknown skill "${name}" (known: ${Object.keys(builders).join(", ")})\n`,
    );
    process.exit(1);
  }
  builder();
}
