#!/usr/bin/env bun
// Builds the Claude Code skills published under skill/:
//   - tutuca       — generated locally from docs/llm/
//   - margaui      — cloned + generated from the margaui repo
//   - immutable-js — cloned from the immutable-js repo's prebuilt skill
//
// Run with no args to build all; pass names to build a subset, e.g.
//   bun scripts/build-skill.js tutuca
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const skillDir = resolve(repo, "skill");

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, { stdio: "inherit", ...opts });
}

function requireBin(cmd) {
  try {
    execFileSync(cmd, ["--version"], { stdio: "ignore" });
  } catch {
    process.stderr.write(`build-skill: required binary not found: ${cmd}\n`);
    process.exit(1);
  }
}

// Shallow-clone `repoUrl` into a temp dir, hand it to `fn(checkout, sha)`,
// then clean the temp dir up regardless of outcome.
function withClone(repoUrl, { branch } = {}, fn) {
  requireBin("git");
  const tmp = mkdtempSync(join(tmpdir(), "tutuca-skill-"));
  try {
    const cloneArgs = ["clone", "--depth", "1"];
    if (branch) cloneArgs.push("--branch", branch);
    cloneArgs.push(repoUrl, tmp);
    process.stdout.write(`cloning ${repoUrl}${branch ? ` (${branch})` : ""} → ${tmp}\n`);
    run("git", cloneArgs);

    const sha = execFileSync("git", ["-C", tmp, "rev-parse", "HEAD"], {
      encoding: "utf8",
    }).trim();
    process.stdout.write(`${repoUrl} commit: ${sha}\n`);

    return fn(tmp, sha);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

// --- tutuca: generated locally from docs/llm/ ------------------------------

const TUTUCA_FRONTMATTER = `---
name: tutuca
description: Use when authoring or reviewing tutuca modules — \`component({...})\` definitions, \`html\\\`...\\\`\` views, \`@\`-directives, \`input\` / \`bubble\` / \`receive\` / \`response\` / \`alter\` handlers, macros, or \`getTests\` exports — or when running the \`tutuca\` CLI (\`lint\` / \`test\` / \`render\` / \`docs\`). Covers the post-edit \`tutuca <module> lint\` → \`test\` → \`render --title "<example>"\` verification recipe.
---

<!-- This file is generated by scripts/build-skill.js from docs/llm/. Do not edit. -->

`;

const TUTUCA_BODY = `# Tutuca

Tutuca is an immutable-state SPA framework. See [core.md](./core.md)
for the framework primer and the post-edit verification recipe
(\`tutuca <module> lint\` → \`test\` → \`render --title "<example>"\`).

## Companion skills

When authoring tutuca code, also load these if available:

- **immutable-js** — every \`immutable\` export is reachable through
  \`tutuca\` (\`List\`, \`IMap\`, \`OMap\`, \`ISet\`, \`Record\`, \`Seq\`,
  \`fromJS\`, \`is\`, …). Reach for it whenever the work touches state
  values.
- **margaui** — the Tailwind v4 / daisyUI-compatible class library.
  Reach for it when the project uses MargaUI / Tailwind class lists in
  \`class=\` / \`:class=\`.

## Routing

| Task                                                                                           | File                            |
| ---------------------------------------------------------------------------------------------- | ------------------------------- |
| Authoring \`component({...})\`, \`html\\\`...\\\`\` views, macros, fields, events, lists, styles | [core.md](./core.md)           |
| CLI commands, flags, exit codes, full linter rule list                                         | [cli.md](./cli.md)             |
| Drag & drop, dynamic bindings (\`*x\`), pseudo-\`x\`, custom seq types, Tailwind/MargaUI | [advanced.md](./advanced.md)   |
| Authoring tests — \`getTests\` shape, calling methods/input/receive/bubble/response/alter handlers, designing handlers for testability | [testing.md](./testing.md) |

Read \`core.md\` first. Reach for \`cli.md\`, \`advanced.md\`, or
\`testing.md\` only when the task touches them — all three are
referenced inline from \`core.md\` so you'll be pointed there when
relevant.
`;

function buildTutuca() {
  const srcDir = resolve(repo, "docs/llm");
  const outDir = resolve(skillDir, "tutuca");

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  for (const name of ["core", "cli", "advanced", "testing"]) {
    cpSync(resolve(srcDir, `${name}.md`), resolve(outDir, `${name}.md`));
  }

  writeFileSync(resolve(outDir, "SKILL.md"), TUTUCA_FRONTMATTER + TUTUCA_BODY);
  process.stdout.write(`built skill/tutuca/ from docs/llm/ → ${outDir}\n`);
}

// --- margaui: cloned + generated from the margaui repo ---------------------

function buildMargaui() {
  const REPO_URL = "https://github.com/marianoguerra/margaui.git";
  const outDir = resolve(skillDir, "margaui");

  requireBin("npm");
  requireBin("python3");

  withClone(REPO_URL, {}, (tmp, sha) => {
    run("npm", ["install"], { cwd: tmp });
    run("npm", ["run", "playground"], { cwd: tmp });
    run("npm", ["run", "gen-skill"], { cwd: tmp });

    const generated = resolve(tmp, ".claude/skills/margaui");
    if (!existsSync(generated)) {
      process.stderr.write(`build-skill: gen-skill produced no output at ${generated}\n`);
      process.exit(1);
    }

    rmSync(outDir, { recursive: true, force: true });
    cpSync(generated, outDir, { recursive: true });
    process.stdout.write(`built skill/margaui/ from ${REPO_URL}@${sha} → ${outDir}\n`);
  });
}

// --- immutable-js: cloned from the immutable-js repo's prebuilt skill ------

function buildImmutable() {
  const REPO_URL = "https://github.com/marianoguerra/immutable-js.git";
  const BRANCH = "7.x";
  const UPSTREAM_SKILL = ".claude/skills/immutable-js";
  const outDir = resolve(skillDir, "immutable-js");

  withClone(REPO_URL, { branch: BRANCH }, (tmp, sha) => {
    const src = resolve(tmp, UPSTREAM_SKILL);
    if (!existsSync(resolve(src, "SKILL.md"))) {
      process.stderr.write(`build-skill: ${UPSTREAM_SKILL}/SKILL.md missing in clone\n`);
      process.exit(1);
    }

    rmSync(outDir, { recursive: true, force: true });
    cpSync(src, outDir, { recursive: true });
    process.stdout.write(
      `built skill/immutable-js/ from ${REPO_URL}@${sha} (${BRANCH}) → ${outDir}\n`,
    );
  });
}

// --- entry point -----------------------------------------------------------

const builders = {
  tutuca: buildTutuca,
  margaui: buildMargaui,
  "immutable-js": buildImmutable,
};

const selected = process.argv.slice(2);
const names = selected.length > 0 ? selected : Object.keys(builders);

for (const name of names) {
  const builder = builders[name];
  if (!builder) {
    process.stderr.write(
      `build-skill: unknown skill "${name}" (known: ${Object.keys(builders).join(", ")})\n`,
    );
    process.exit(1);
  }
  builder();
}
